apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "panda-hello.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "panda-hello.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "panda-hello.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "panda-hello.name" . }}
    spec:
      {{- if .imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ include "panda-hello.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080